# generation hyper-parameters
max_len: 512
penalty_alpha: 0.6
top_k: 10
top_p: 0.7
random_prefix_len: 5
sample_num: 2
decoding_method: sampling
generate_len: 512

# some train configuration, more can be found under dsconfig folder
train:
    seed: 0
    warmup_rate: 0.1
    epochs: 3
    max_shard_size: 5GB
